### ISSUE TITLE
Agregar un coc

### ISSUE THREAD

**Issue by 4k1k0** [gophers-mx/recursos#1]
Podríamos (y deberíamos) agregar un coc  ¿Qué piensan? :cow: 

¿Funciona [covenant](https://www.contributor-covenant.org/)?

**Comment by zeroidentidad** [comment]
Una versión de https://golang.org/conduct

**Comment by Graywolf9** [comment]
https://github.com/gophers-mx/codigo-de-conducta

¿Este no cumple con esa función?

**Comment by danvergara** [comment]
@Graywolf9 Este issue es viejo, ya deberíamos cerrarlo de hecho.
