### ISSUE TITLE
Convertir el markdown del repo de recursos a una github page

### ISSUE THREAD

**Issue by danvergara** [gophers-mx/recursos#6]
Para hacer todavía más accesible el contenido del repo de los recursos, deberíamos convertir el contenido markdown a una github page.

Para más referencias [aquí](https://nicolas-van.github.io/easy-markdown-to-github-pages/).

**Comment by 4k1k0** [comment]
:eyes:  Va va va que se arme

**Comment by danvergara** [comment]
Cierro issue. Creo que lo siguiente es usar el nuevo dominio.
